
function TermOfUseComponent(){
    return(
        <>
            <h2>Logistics Terms and Conditions</h2>
<p><strong>GOFAZ ROSSUL LOGISTICS TERMS AND  CONDITIONS OF CONTRACT</strong> <br />
    <strong>By acceptance of services of Gofaz Rossul Logistics or Agents, Customer and any other  party with an interest in the goods agree to these Terms and Conditions of  Contract.</strong><br />
    <strong>Gofaz Rossul Logistics Terms&nbsp;and Conditions&nbsp;are Subject&nbsp;to  Change&nbsp;at Gofaz Rossul Logistics&rsquo; Sole Discretion Without Notice&nbsp;to Any Parties &ndash; Rev.  2/10</strong><br />
    <br />
    <strong>I. Definitions:</strong><br />
    <strong>Gofaz Rossul Logistics:</strong> Gofaz Rossul Logistics, is hereinafter  referred to as Gofaz Rossul Logistics. Gofaz Rossul Logistics as referenced hereinafter shall include, but is not  limited to the following services: electrical (a/k/a TSE/Trade Show  Electrical), rigging, material handling, installation and dismantle, and  logistics provided by Gofaz Rossul Logistics personnel to exhibitor pursuant to any purchase of  Services. <strong>Agents:</strong> Gofaz Rossul Logistics&rsquo; agents, sub-contractors, carriers, and  the agents of each; <strong>Customer:</strong> Exhibitor or other party  requesting Services from Gofaz Rossul Logistics; <strong>Goods:</strong> Exhibits, property, and  commodities of any type for which Gofaz Rossul Logistics is requested to perform Services; <strong>Carrier:</strong> Motor carrier, van line, air carrier, or air or surface freight forwarder; <strong>Shipper:</strong> Party who tenders Goods to Carrier for transportation; <strong>Cold Storage:</strong> Holding of Goods in a climate controlled area; <strong>Consignee:</strong> Party to whom goods are shipped; <strong>ICCTA:</strong> Part B 49 U.S.C.  Sections 13101 &ndash; 14914, of the ICC Termination Act of 1995; <strong>HAZMAT:</strong> Those articles, commodities and/or goods defined as hazardous in 49 CFR Parts  s171-177. <strong>Services:</strong> Warehousing, transportation, drayage,  and/or related services.<br />
    <strong><br />
  II. Scope:</strong> <br />
  These Terms and Conditions shall be binding upon Customer, Gofaz Rossul Logistics, and their  respective Agents, representatives, Shipper and Consignee, including but not  limited to Customer contracted labor such as Customer Appointed Contractors and  Installation and Dismantle Companies, and any other party with an interest in  the Goods. Each shall have the benefit of and be bound by all provisions stated  herein, including but not limited to time limits and limitations of liability.<br />
  <strong><br />
  III. Customer Obligations:</strong> <br />
  a. <u>Payment for Services.</u> Customer, Shipper, and Consignee shall be jointly liable for all unpaid charGofaz Rossul Logistics  for services performed by Gofaz Rossul Logistics or Agents. Customer authorizes Gofaz Rossul Logistics to charge its  credit card directly for services rendered on Customer&rsquo;s behalf after departure  by placing an order on-line, via fax, phone or through a work order on site.<br />
  b. <u>Credit Terms.</u> All  charGofaz Rossul Logistics are due before Services are performed unless other arrangements have  been made in advance. Gofaz Rossul Logistics has the right to require prepayment or guarantee of  the charGofaz Rossul Logistics at the time of request for Services. A failure to pay timely will  result in Customer having to pay in cash in advance for future services. Gofaz Rossul Logistics  retains its right to hold Customers&rsquo; Goods for non-payment. If a credit card is  provided to Gofaz Rossul Logistics, Gofaz Rossul Logistics is authorized to bill to such credit card any unpaid  charGofaz Rossul Logistics for services provided to Customer, including charGofaz Rossul Logistics for return  shipping. Any charGofaz Rossul Logistics not paid within 30 days of delivery will be subject to  interest at 1 1/2% per month until paid.<br />
  c. <u>Proper Description.</u> Customer is obligated to disclose to Gofaz Rossul Logistics and Carrier if Customer&rsquo;s packaGofaz Rossul Logistics  contain items that are considered Hazardous Materials or Dangerous Goods.  Customer has the obligation to ensure that each package is properly and  completely described, is properly marked and addressed, and is packaged  adequately to protect the contents during transportation. Customer must provide  all documentation for HAZMAT shipping as required by the Department of  Transportation. Customer hereby agrees to provide Gofaz Rossul Logistics and Carrier with accurate  information in order to allow for all proper disclosures to be made on Customer&rsquo;s  shipment. Customer is responsible for all placarding.<br />
  <strong><br />
  IV. Mutual Obligations:</strong> <br />
  <br />
  <strong>A.</strong> <u>ICCTA Waiver.</u> Customer and Gofaz Rossul Logistics expressly and mutually waive, to the extent permissible under  law, any and all rights and remedies each may have under ICCTA to the extent  those provisions conflict with these Terms and Conditions.<br />
  <br />
  <strong>B.</strong> <u>Customer to Gofaz Rossul Logistics.</u> Customer shall defend, hold harmless and indemnify Gofaz Rossul Logistics from and against any  claims, lawsuits, demands, liability, costs and expenses, including reasonable  attorney&rsquo;s fees and court costs, resulting from any injury to or death of  persons, or damage to property other than Goods, relating to or arising from  performance of Services herein. Customer agrees to indemnify and hold Gofaz Rossul Logistics  harmless for any and all acts of its representatives and agents, including but  not limited to Customer Appointed Contractors and Installation and Dismantle  Companies, any subtenant or other user of its space or any agents or employees  engaged in business on behalf of Customer or present at Customer&rsquo;s invitation,  including supervision of labor secured through Gofaz Rossul Logistics. Customer&rsquo;s obligations  under this provision shall not apply to Gofaz Rossul Logistics&rsquo; own negligence and/or willful  misconduct. Unless otherwise agreed, Customer agrees to indemnify and Gofaz Rossul Logistics  harmless for any transportation charGofaz Rossul Logistics. <strong>CUSTOMER ACKNOWLED Gofaz Rossul Logistics THAT THE  SHOW SITE IS AN ACTIVE WORK ZONE AND CUSTOMER, ITS AGENTS, EMPLOYEES AND  REPRESENTATIVES ARE PRESENT AT THEIR OWN RISK.</strong><br />
  <br />
  <strong>C.</strong> <u>Gofaz Rossul Logistics to Customer.</u> To  the extent of Gofaz Rossul Logistics&rsquo; own negligence and/or willful misconduct, and subject to the  limitations of liability below, Gofaz Rossul Logistics shall defend, hold harmless and indemnify  Customer from and against any claims, lawsuits, demands, liability, costs and  expenses, including reasonable attorney&rsquo;s fees and court costs, resulting from  any injury to or death of persons, or damage to property other than Goods. Gofaz Rossul Logistics&rsquo;  obligations under this provision shall not apply to claims for bodily injury  arising a) from Customer&rsquo;s presence in areas which have been marked as &ldquo;off  limits to exhibitors&rdquo;; and b) when exhibitors are present in the facility prior  or subsequent to the effective dates or hours of exhibitor&rsquo;s space lease with  show management.<br />
  <strong><br />
  V. DISCLAIMER AND LIMITATION  OF LIABILITY</strong> <br />
  <strong>UNDER NO CIRCUMSTANCES WILL ANY PARTY BE LIABLE FOR SPECIAL, INCIDENTAL,  CONSEQUENTIAL, INDIRECT OR PUNITIVE DAMAGofaz Rossul Logistics, INCLUDING BUT NOT LIMITED TO LOSS  OF PROFITS OR INCOME. Gofaz Rossul Logistics SHALL BE LIABLE, SUBJECT TO THE LIMITATIONS CONTAINED  HEREIN, FOR LOSS OR DAMAGE TO GOODS ONLY IF SUCH LOSS OR DAMAGE IS CAUSED BY  THE DIRECT NEGLIGENCE OR WILLFUL MISCONDUCT OF Gofaz Rossul Logistics. CLAIMS PRESENTED FOR LOSS  OR DAMAGE ARISING OUT OF INCIDENTS REFERENCED IN SECTION VI HEREIN WILL BE  DENIED. </strong><br />
  <strong><br />
  VI. No Liability for Loss or  Damage to Goods</strong> <br />
  <strong>A.</strong> <u>Condition of Goods</u>:  Gofaz Rossul Logistics shall not be liable for damage, loss, or delay to uncrated freight, freight  improperly packed, glass breakage or concealed damage. Gofaz Rossul Logistics shall not be liable  for ordinary wear and tear in handling of Goods or for damage to shrink wrapped  Goods. All Goods shall be able to withstand handling by heavy equipment,  including but not limited to forklifts, cranes, or dollies. It is the  Customer&rsquo;s responsibility to ensure that Goods are packaged correctly prior to  shipment or movement on or off the Show floor.<br />
  <strong><br />
  B.</strong> <u>Receipt of Goods</u>:  Gofaz Rossul Logistics shall not be liable for Goods received without receipts, freight bills, or  specified piece count on receipts or freight bills, or for bulk shipments  (i.e., UPS, air freight, or van lines). Such Goods shall be delivered to booth  without the guarantee of piece count or condition.<br />
  <br />
  <strong>C.</strong> <u>Force Majeure</u>: Gofaz Rossul Logistics  shall not be liable for loss or damage that results from Acts of God, weather  conditions, act or default of Customer, shipper, or the owner of the Goods,  inherent nature of the Goods, public enemy, public authority, labor disputes,  and acts of terrorism or war.<br />
  <br />
  <strong>D.</strong> <u>Cold Storage</u>: Goods  requiring cold storage are stored at Customer&rsquo;s own risk. Gofaz Rossul Logistics assumes no  liability or responsibility for Cold Storage.<br />
  <br />
  <strong>E.</strong> <u>Unattended Goods</u>: Gofaz Rossul Logistics  assumes no liability for loss or damage to unattended Goods received at Show  Site at any time from the point of receipt of inbound Goods until the loading  of the outbound Goods, including the entire term of the respective show or  exhibition. Customer is responsible for insuring its own Goods for any and all  risk of loss.<br />
  <br />
  <strong>F.</strong> <u>Empty Storage</u>: Gofaz Rossul Logistics  assumes no liability for loss or damage to Goods or crates, or the contents  therein, while containers are in Empty Storage. It is Customer&rsquo;s sole  responsibility to affix the appropriate labels available at the Gofaz Rossul Logistics Service  Desk for empty container storage, and ensures that any pre-existing empty  labels are removed.<br />
  <br />
  <strong>G.</strong> <u>Forced Freight</u>: Gofaz Rossul Logistics  is not liable for Customer Goods left on the show floor after the show closing  deadline, with or without a Material Handling Services/Straight Bill of Lading  signed by Customer. It is Customer&rsquo;s responsibility to complete accurate  paperwork for shipping and to ensure Customer Goods are properly labeled. If  Customer Goods remain on the floor after the show closing deadline, Gofaz Rossul Logistics has the  right to remove the Customer Goods. Gofaz Rossul Logistics is authorized by Customer to proceed in  the manner chosen by Customer on the Order of Material Handling  Services/Straight Bill of Lading, if one has been completed, or otherwise, to  ship Customer Goods at the discretion of Gofaz Rossul Logistics and at Customer&rsquo;s expense. Gofaz Rossul Logistics  shall incur no liability for such shipment. Gofaz Rossul Logistics retains the right to dispose of  Customer Goods without liability if left on the show floor unattended, without  labels or not correctly labeled.<br />
  <br />
  <strong>H.</strong> <u>Concealed Damage</u>:  Gofaz Rossul Logistics shall not be liable for concealed loss or damage including but not limited  to; glass, electronic equipment, prototypes, original art, uncrated Goods, or  improperly packaged or labeled Goods. <br />
  <br />
  <strong>  I.</strong> <u>Unattended Booth</u>:  Gofaz Rossul Logistics shall not be liable for any loss or damage occurring while the Goods are  unattended in Customer&rsquo;s booth at any time, including, but not limited to, the  time the Goods are delivered to the dock until the time the Goods are received  by Customer&rsquo;s chosen carrier. All Material Handling Forms and/or Straight Bills  of Lading covering outgoing Goods submitted to Gofaz Rossul Logistics will be checked at the time  of pickup from the booth and corrections to the count or condition will be  documented where discrepancies exist.<br />
  <strong><br />
  VII. Measure of Damage</strong> <br />
  <strong>A.</strong> <u>Sole Relief</u>: If  found liable for any loss, Gofaz Rossul Logistics&rsquo; sole and exclusive maximum liability for loss  or damage to Customer&rsquo;s Goods is limited to $.50 (USD) per pound with a maximum  liability of $100.00 (USD) per container, or $1,500.00 (USD) per shipment  whichever is less.<br />
  <strong><br />
  B.</strong> <u>Labor</u>: Gofaz Rossul Logistics assumes  no liability for loss, damage, or bodily injury arising out of Customer&rsquo;s  supervision of Gofaz Rossul Logistics provided union labor. If Gofaz Rossul Logistics supervises labor for a fee, Gofaz Rossul Logistics  shall be liable only for actions or claims arising out of its negligent  supervision. Such liability shall be limited to the cost to Customer of the  supervised labor or the depreciated value of the Goods, whichever is less. If  Customer elects to use unsupervised labor, then Customer assumes all liability  for the actions or claims that arise out of such work, including but not  limited to loss, damage or bodily injury and shall provide Gofaz Rossul Logistics and show  management with an indemnity, including defense costs, for any claims that  result from Customers&rsquo; supervision or failure to supervise assigned labor.<br />
  <strong><br />
  VIII. Miscellaneous</strong> <br />
  <strong>A.</strong> <u>Insurance</u>: <strong>Gofaz Rossul Logistics  IS <u>NOT</u> AN INSURANCE COMPANY AND DOES NOT OFFER OR PROVIDE INSURANCE</strong>.  It is the obligation of Customer to ensure Goods are insured at all times. Loss  or theft of the Goods in storage or in transit to and from the show and or  while on the show floor is the sole responsibility of Customer. Gofaz Rossul Logistics recommends  Customer arrange for all Risk Coverage.<br />
  <br />
  <strong>B.</strong> <u>Notice of Loss or  Damage</u>: In order to have a valid claim, notice of loss or damage to Goods  must be given to Gofaz Rossul Logistics or its agent within 24 hours of occurrence (as evidenced  in an Incident Report completed at Show Site by Gofaz Rossul Logistics) or delivery of outbound  Goods.<br />
  <strong><br />
  C.</strong> <u>Filing of Claim</u>:  Any claim for loss or damage to Goods must be in writing, containing facts  sufficient to identify the Goods, asserting liability for alleged loss or  damage, and making claim for the payment of a specified or determinable amount  of money. Such claim must be filed with the appropriate party within the time  limits specified herein. Damage reports, incident reports, inspection reports,  notations of shortage or damage on freight bills or other documents, do not  constitute filing of a claim.<br />
  Claims for Goods alleged to be lost, stolen or damaged at the Show Site must be  received in writing by Gofaz Rossul Logistics within <strong>thirty (30)</strong> days after the  close of the show.<br />
  Claims for Goods alleged to be lost or damaged <strong>during transit</strong> must be received by the responsible party within nine (9) months of date of  delivery of Goods. GOFAZ ROSSUL LOGISTICS subcontracts the movement of Goods to third  party carriers. Claims for damage in transit should be made directly with your  carrier as shown on the Material Handling form/ Bill of Lading.<br />
  In the event of a dispute with Gofaz Rossul Logistics, Customer will not withhold payment or any  amount due Gofaz Rossul Logistics for Services as an offset against the amount of the alleged loss  or damage. Customer agrees to pay Gofaz Rossul Logistics prior to the close of the show for all  such charGofaz Rossul Logistics and further agrees that any claim Customer may have against Gofaz Rossul Logistics  shall be pursued independently by Customer as a separate action to be resolved  on its own merits. Gofaz Rossul Logistics retains the right to pursue collection on amounts owed  after show close, without regard to any amount alleged to be owed for damage,  or loss.<br />
  <br />
  <strong>D.</strong> <u>Filing of Suit</u>: Any  action at law regarding loss or damage to Goods must be filed within two (2)  years of the date of declination of any part of a claim.<br />
  <br />
  <strong>E.</strong> <u>Excess Declared Value</u>:  Customer may obtain a higher limitation of liability, up to $20,000 per  shipment as follows: <strong>1. To request Excess Declared Value,</strong> (a)  Customer must state the Excess Declared Value amount in the space provided on  the Gofaz Rossul Logistics services order forms, and on the Material Handling Order Form; and; (b)  Check the box requesting Excess Declared Value, and; (c) Pay the appropriate  charge for Excess Declared Value prior to shipment date. <strong>2. Cost &ndash;  Excess Declared Value</strong> is available from Gofaz Rossul Logistics for $2.00 per $100.00 of  Excess Declared Value with a $100.00 minimum charge. <strong>3. Not Insurance &ndash;  Excess Declared Value is NOT INSURANCE. Gofaz Rossul Logistics IS NOT AN INSURANCE COMPANY AND  DOES NOT OFFER OR PROVIDE INSURANCE.</strong> Gofaz Rossul Logistics will not be liable or  responsible for loss or damage to Customer Goods, unless such loss or damage is  caused by Gofaz Rossul Logistics&rsquo; negligence.<br />
  <strong>Excess Declared Value is not available for: plasma screens, LCD  screens, electronic equipment, original art, one of a kind items and/or  prototypes. Declared Value may never be purchased in excess of $20,000 for  purposes of this provision.</strong> Gofaz Rossul Logistics&rsquo; liability in all circumstances shall  be limited to the amount of this cap. Notwithstanding the foregoing, all  shipments containing the following items of extraordinary value are limited to  the maximum declared value of $500.00 (USD). 1. Clocks, jewelry, including  costume jewelry, furs or items trimmed in fur; 2. Coins, money, currency, gift  certificates, gift cards, debit cards or credit cards; 3. Personal effects  including without limitation, clothing, paper and documents or any other items  of extraordinary value. In addition, any Declared Value in excess of the  maximum stated above is null and void and the acceptance by Gofaz Rossul Logistics for carriage of  any shipment with a declared value in excess of the allowed maximums does not  constitute a waiver of these maximums. Under no circumstance will Gofaz Rossul Logistics be  responsible for any incidental, consequential or punitive damaGofaz Rossul Logistics due to loss,  damage, theft or delay of Goods or any other causes. <br />
  <strong><br />
  IX. Jurisdiction, Choice of  Forum</strong> <br />
  This Agreement shall be governed by and construed in accordance with the  applicable laws of the United States or, alternatively, and depending on  jurisdiction, the laws of the State of Oregon. The parties hereby submit to  jurisdiction and venue in the United States Federal District Court of Oregon,  or as applicable depending upon jurisdiction, the Multnomah County Circuit  Court in Portland, Oregon.<br />
  <strong><br />
  X. Advanced  Warehousing/Temporary Storage/Long Term Storage</strong> <br />
  All terms and conditions relative to Advanced Warehousing/Temporary  Storage/Long Term Storage are contained in separate agreements titled &ldquo;Storage  Agreement&rdquo;. In the event that a Storage Agreement is not executed between the  parties, the following shall apply with respect to Gofaz Rossul Logistics&rsquo; liability for  Customer&rsquo;s Goods. The responsibility of Gofaz Rossul Logistics with respect to Customer&rsquo;s Goods is  limited to the exercise of ordinary care and diligence in handling and storing  of Customer&rsquo;s Goods. Gofaz Rossul Logistics shall be liable only for loss or damage to Goods  caused by Gofaz Rossul Logistics&rsquo; sole negligence. Gofaz Rossul Logistics&rsquo; liability is limited to $.60 (USD) per  pound with a maximum liability of $100.00 (USD) per container, or $1,500.00  (USD) per shipment whichever is less. In case of partial loss or damage, the  maximum liability shall be prorated based on weight. Gofaz Rossul Logistics is not responsible for  any loss or damage to Goods caused by, but not limited to fire, theft, the  elements, vandalism, moisture, vermin, mechanical breakdown or failure,  freezing or chanGofaz Rossul Logistics in temperature, as well as any other causes beyond Gofaz Rossul Logistics&rsquo;  immediate control. Gofaz Rossul Logistics is not responsible for the marring, scratching or  breakage of glass or other fragile items. Gofaz Rossul Logistics is not liable for the mechanical  functions of instruments or appliances even if such articles are packed or  unpacked by Gofaz Rossul Logistics. In no event shall Gofaz Rossul Logistics be liable for special, incidental,  indirect or consequential damaGofaz Rossul Logistics, including business loss of any kind, resulting  from any damage to or loss of the Goods or from any act or failure to act.  Customer pays storage fees or costs for advance warehousing for use of the  space only. There is no guarantee of security or representations made by Gofaz Rossul Logistics as  to appropriateness of the conditions for Customer&rsquo;s Goods. The risk of loss  remains Customer&rsquo;s alone and Gofaz Rossul Logistics recommends the Customer carry and maintain  insurance in amounts sufficient to cover its risk.<br />
  <strong><br />
  These terms apply to your  order.</strong> </p>
        </>
    )
}

export default TermOfUseComponent